dynamic.1.name=svc_cloudflared
dynamic.1.source=systemctl is-active cloudflared
dynamic.1.regexp=(.*)
dynamic.1.default=inactive

dynamic.2.name=svc_docker
dynamic.2.source=systemctl is-active docker
dynamic.2.regexp=(.*)
dynamic.2.default=inactive

dynamic.3.name=svc_fail2ban
dynamic.3.source=systemctl is-active fail2ban
dynamic.3.regexp=(.*)
dynamic.3.default=inactive

dynamic.4.name=svc_ssh
dynamic.4.source=systemctl is-active ssh
dynamic.4.regexp=(.*)
dynamic.4.default=inactive

dynamic.5.name=svc_rpimonitor
dynamic.5.source=systemctl is-active rpimonitor
dynamic.5.regexp=(.*)
dynamic.5.default=inactive

web.status.1.content.2.title="Services"
web.status.1.content.2.icon=daemons.png
web.status.1.content.2.line.1=Label(data.svc_cloudflared,"=='active'","cloudflared","success")+Label(data.svc_cloudflared,"!='active'","cloudflared","danger")+" "+Label(data.svc_docker,"=='active'","docker","success")+Label(data.svc_docker,"!='active'","docker","danger")
web.status.1.content.2.line.2=Label(data.svc_fail2ban,"=='active'","fail2ban","success")+Label(data.svc_fail2ban,"!='active'","fail2ban","danger")+" "+Label(data.svc_ssh,"=='active'","ssh","success")+Label(data.svc_ssh,"!='active'","ssh","danger")
web.status.1.content.2.line.3=Label(data.svc_rpimonitor,"=='active'","rpimonitor","success")+Label(data.svc_rpimonitor,"!='active'","rpimonitor","danger")
