# Last 3 successful SSH logins: user|ip|Mon DD HH:MM;...
dynamic.1.name=last_success
dynamic.1.source=/usr/local/bin/rpi-logins Accepted
dynamic.1.regexp=(.*)
dynamic.1.postprocess=$1
dynamic.1.default=

# Last 3 failed SSH login attempts: user|ip|Mon DD HH:MM;...
dynamic.2.name=last_failed
dynamic.2.source=/usr/local/bin/rpi-logins Failed
dynamic.2.regexp=(.*)
dynamic.2.postprocess=$1
dynamic.2.default=
