static.1.name=boot_total
static.1.source=df /boot/firmware
static.1.regexp=\S+\s+(\d+)
static.1.postprocess=$1/1024

dynamic.1.name=boot_used
dynamic.1.source=df /boot/firmware
dynamic.1.regexp=\S+\s+\d+\s+(\d+)
dynamic.1.postprocess=$1/1024
dynamic.1.rrd=GAUGE

web.status.1.content.1.title="Storage"
web.status.1.content.1.icon=usb_hdd.png
web.status.1.content.1.line.1="<b>/boot/firmware</b> Used: <b>"+KMG(data.boot_used,'M')+"</b> ("+Percent(data.boot_used,data.boot_total,'M')+") Free: <b>"+KMG(data.boot_total-data.boot_used,'M')+"</b> Total: <b>"+KMG(data.boot_total,'M')+"</b>"
web.status.1.content.1.line.2=ProgressBar(data.boot_used,data.boot_total)
